//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Downloads
{
    [Serializable]
    public class CollisionDetectorMsg : Message
    {
        public const string k_RosMessageName = "Downloads/CollisionDetector";
        public override string RosMessageName => k_RosMessageName;

        public bool isCollision;

        public CollisionDetectorMsg()
        {
            this.isCollision = false;
        }

        public CollisionDetectorMsg(bool isCollision)
        {
            this.isCollision = isCollision;
        }

        public static CollisionDetectorMsg Deserialize(MessageDeserializer deserializer) => new CollisionDetectorMsg(deserializer);

        private CollisionDetectorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.isCollision);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.isCollision);
        }

        public override string ToString()
        {
            return "CollisionDetectorMsg: " +
            "\nisCollision: " + isCollision.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
