//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaPositionalControl
{
    [Serializable]
    public class GripperForceGraspingResponse : Message
    {
        public const string k_RosMessageName = "kinova_positional_control/GripperForceGrasping";
        public override string RosMessageName => k_RosMessageName;

        public bool state;

        public GripperForceGraspingResponse()
        {
            this.state = false;
        }

        public GripperForceGraspingResponse(bool state)
        {
            this.state = state;
        }

        public static GripperForceGraspingResponse Deserialize(MessageDeserializer deserializer) => new GripperForceGraspingResponse(deserializer);

        private GripperForceGraspingResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GripperForceGraspingResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
