//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaPositionalControl
{
    [Serializable]
    public class GripperForceGraspingRequest : Message
    {
        public const string k_RosMessageName = "kinova_positional_control/GripperForceGrasping";
        public override string RosMessageName => k_RosMessageName;

        public float target_current;

        public GripperForceGraspingRequest()
        {
            this.target_current = 0.0f;
        }

        public GripperForceGraspingRequest(float target_current)
        {
            this.target_current = target_current;
        }

        public static GripperForceGraspingRequest Deserialize(MessageDeserializer deserializer) => new GripperForceGraspingRequest(deserializer);

        private GripperForceGraspingRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.target_current);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.target_current);
        }

        public override string ToString()
        {
            return "GripperForceGraspingRequest: " +
            "\ntarget_current: " + target_current.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
