//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaPositionalControl
{
    [Serializable]
    public class GripperPositionRequest : Message
    {
        public const string k_RosMessageName = "kinova_positional_control/GripperPosition";
        public override string RosMessageName => k_RosMessageName;

        public float position;

        public GripperPositionRequest()
        {
            this.position = 0.0f;
        }

        public GripperPositionRequest(float position)
        {
            this.position = position;
        }

        public static GripperPositionRequest Deserialize(MessageDeserializer deserializer) => new GripperPositionRequest(deserializer);

        private GripperPositionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "GripperPositionRequest: " +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
