//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaPositionalControl
{
    [Serializable]
    public class PidVelocityLimitResponse : Message
    {
        public const string k_RosMessageName = "kinova_positional_control/PidVelocityLimit";
        public override string RosMessageName => k_RosMessageName;

        public bool state;

        public PidVelocityLimitResponse()
        {
            this.state = false;
        }

        public PidVelocityLimitResponse(bool state)
        {
            this.state = state;
        }

        public static PidVelocityLimitResponse Deserialize(MessageDeserializer deserializer) => new PidVelocityLimitResponse(deserializer);

        private PidVelocityLimitResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "PidVelocityLimitResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
