//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KinovaPositionalControl
{
    [Serializable]
    public class PidVelocityLimitRequest : Message
    {
        public const string k_RosMessageName = "kinova_positional_control/PidVelocityLimit";
        public override string RosMessageName => k_RosMessageName;

        public double data;

        public PidVelocityLimitRequest()
        {
            this.data = 0.0;
        }

        public PidVelocityLimitRequest(double data)
        {
            this.data = data;
        }

        public static PidVelocityLimitRequest Deserialize(MessageDeserializer deserializer) => new PidVelocityLimitRequest(deserializer);

        private PidVelocityLimitRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.data);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.data);
        }

        public override string ToString()
        {
            return "PidVelocityLimitRequest: " +
            "\ndata: " + data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
