//Do not edit! This file was generated by Unity-ROS MessageGeneration.
// CORRECTED: actual gopher_ros_clearcore/Position.msg layout is
//   float32 position
//   float32 speed_fraction
// Both fields are float32 → 8 bytes total.
// The original auto-generated file used (double position, double velocity) = 16 bytes.
// An intermediate fix used (float position, double speed_fraction) = 12 bytes.
// Both were wrong; confirmed via rostopic echo: speed_fraction was 0.0 because
// the first 4 bytes of float64(0.5) in little-endian are 0x00000000 = float32(0.0).
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.GopherRosClearcore
{
    [Serializable]
    public class PositionMsg : Message
    {
        public const string k_RosMessageName = "gopher_ros_clearcore/Position";
        public override string RosMessageName => k_RosMessageName;

        public float position;        // float32 — 4 bytes  (first field)
        public float speed_fraction;  // float32 — 4 bytes  (second field)

        public PositionMsg()
        {
            this.position       = 0.0f;
            this.speed_fraction = 0.0f;
        }

        public PositionMsg(float position, float speed_fraction)
        {
            this.position       = position;
            this.speed_fraction = speed_fraction;
        }

        public static PositionMsg Deserialize(MessageDeserializer deserializer) => new PositionMsg(deserializer);

        private PositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            deserializer.Read(out this.speed_fraction);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.speed_fraction);
        }

        public override string ToString()
        {
            return "PositionMsg: " +
            "\nposition: " + position.ToString() +
            "\nspeed_fraction: " + speed_fraction.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
