//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class BaseCyclic_ServiceVersionMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/BaseCyclic_ServiceVersion";
        public override string RosMessageName => k_RosMessageName;

        public const uint RESERVED_0 = 0;
        public const uint CURRENT_VERSION = 1;

        public BaseCyclic_ServiceVersionMsg()
        {
        }
        public static BaseCyclic_ServiceVersionMsg Deserialize(MessageDeserializer deserializer) => new BaseCyclic_ServiceVersionMsg(deserializer);

        private BaseCyclic_ServiceVersionMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "BaseCyclic_ServiceVersionMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
