//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class BaseCyclic_CustomDataMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/BaseCyclic_CustomData";
        public override string RosMessageName => k_RosMessageName;

        public uint frame_id;
        public uint custom_data_0;
        public uint custom_data_1;
        public uint custom_data_2;
        public uint custom_data_3;
        public uint custom_data_4;
        public uint custom_data_5;
        public uint custom_data_6;
        public uint custom_data_7;
        public ActuatorCustomDataMsg[] actuators_custom_data;
        public InterconnectCyclic_CustomDataMsg interconnect_custom_data;

        public BaseCyclic_CustomDataMsg()
        {
            this.frame_id = 0;
            this.custom_data_0 = 0;
            this.custom_data_1 = 0;
            this.custom_data_2 = 0;
            this.custom_data_3 = 0;
            this.custom_data_4 = 0;
            this.custom_data_5 = 0;
            this.custom_data_6 = 0;
            this.custom_data_7 = 0;
            this.actuators_custom_data = new ActuatorCustomDataMsg[0];
            this.interconnect_custom_data = new InterconnectCyclic_CustomDataMsg();
        }

        public BaseCyclic_CustomDataMsg(uint frame_id, uint custom_data_0, uint custom_data_1, uint custom_data_2, uint custom_data_3, uint custom_data_4, uint custom_data_5, uint custom_data_6, uint custom_data_7, ActuatorCustomDataMsg[] actuators_custom_data, InterconnectCyclic_CustomDataMsg interconnect_custom_data)
        {
            this.frame_id = frame_id;
            this.custom_data_0 = custom_data_0;
            this.custom_data_1 = custom_data_1;
            this.custom_data_2 = custom_data_2;
            this.custom_data_3 = custom_data_3;
            this.custom_data_4 = custom_data_4;
            this.custom_data_5 = custom_data_5;
            this.custom_data_6 = custom_data_6;
            this.custom_data_7 = custom_data_7;
            this.actuators_custom_data = actuators_custom_data;
            this.interconnect_custom_data = interconnect_custom_data;
        }

        public static BaseCyclic_CustomDataMsg Deserialize(MessageDeserializer deserializer) => new BaseCyclic_CustomDataMsg(deserializer);

        private BaseCyclic_CustomDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            deserializer.Read(out this.custom_data_0);
            deserializer.Read(out this.custom_data_1);
            deserializer.Read(out this.custom_data_2);
            deserializer.Read(out this.custom_data_3);
            deserializer.Read(out this.custom_data_4);
            deserializer.Read(out this.custom_data_5);
            deserializer.Read(out this.custom_data_6);
            deserializer.Read(out this.custom_data_7);
            deserializer.Read(out this.actuators_custom_data, ActuatorCustomDataMsg.Deserialize, deserializer.ReadLength());
            this.interconnect_custom_data = InterconnectCyclic_CustomDataMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.Write(this.custom_data_0);
            serializer.Write(this.custom_data_1);
            serializer.Write(this.custom_data_2);
            serializer.Write(this.custom_data_3);
            serializer.Write(this.custom_data_4);
            serializer.Write(this.custom_data_5);
            serializer.Write(this.custom_data_6);
            serializer.Write(this.custom_data_7);
            serializer.WriteLength(this.actuators_custom_data);
            serializer.Write(this.actuators_custom_data);
            serializer.Write(this.interconnect_custom_data);
        }

        public override string ToString()
        {
            return "BaseCyclic_CustomDataMsg: " +
            "\nframe_id: " + frame_id.ToString() +
            "\ncustom_data_0: " + custom_data_0.ToString() +
            "\ncustom_data_1: " + custom_data_1.ToString() +
            "\ncustom_data_2: " + custom_data_2.ToString() +
            "\ncustom_data_3: " + custom_data_3.ToString() +
            "\ncustom_data_4: " + custom_data_4.ToString() +
            "\ncustom_data_5: " + custom_data_5.ToString() +
            "\ncustom_data_6: " + custom_data_6.ToString() +
            "\ncustom_data_7: " + custom_data_7.ToString() +
            "\nactuators_custom_data: " + System.String.Join(", ", actuators_custom_data.ToList()) +
            "\ninterconnect_custom_data: " + interconnect_custom_data.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
