//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class BaseCyclic_FeedbackMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/BaseCyclic_Feedback";
        public override string RosMessageName => k_RosMessageName;

        public uint frame_id;
        public BaseFeedbackMsg @base;
        public ActuatorFeedbackMsg[] actuators;
        public InterconnectCyclic_FeedbackMsg interconnect;

        public BaseCyclic_FeedbackMsg()
        {
            this.frame_id = 0;
            this.@base = new BaseFeedbackMsg();
            this.actuators = new ActuatorFeedbackMsg[0];
            this.interconnect = new InterconnectCyclic_FeedbackMsg();
        }

        public BaseCyclic_FeedbackMsg(uint frame_id, BaseFeedbackMsg @base, ActuatorFeedbackMsg[] actuators, InterconnectCyclic_FeedbackMsg interconnect)
        {
            this.frame_id = frame_id;
            this.@base = @base;
            this.actuators = actuators;
            this.interconnect = interconnect;
        }

        public static BaseCyclic_FeedbackMsg Deserialize(MessageDeserializer deserializer) => new BaseCyclic_FeedbackMsg(deserializer);

        private BaseCyclic_FeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.frame_id);
            this.@base = BaseFeedbackMsg.Deserialize(deserializer);
            deserializer.Read(out this.actuators, ActuatorFeedbackMsg.Deserialize, deserializer.ReadLength());
            this.interconnect = InterconnectCyclic_FeedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.frame_id);
            serializer.Write(this.@base);
            serializer.WriteLength(this.actuators);
            serializer.Write(this.actuators);
            serializer.Write(this.interconnect);
        }

        public override string ToString()
        {
            return "BaseCyclic_FeedbackMsg: " +
            "\nframe_id: " + frame_id.ToString() +
            "\n@base: " + @base.ToString() +
            "\nactuators: " + System.String.Join(", ", actuators.ToList()) +
            "\ninterconnect: " + interconnect.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
