//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class CustomDataUnitMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/CustomDataUnit";
        public override string RosMessageName => k_RosMessageName;

        public uint custom_data_0;
        public uint custom_data_1;
        public uint custom_data_2;
        public uint custom_data_3;
        public uint custom_data_4;
        public uint custom_data_5;
        public uint custom_data_6;
        public uint custom_data_7;
        public uint custom_data_8;
        public uint custom_data_9;
        public uint custom_data_10;
        public uint custom_data_11;
        public uint custom_data_12;
        public uint custom_data_13;
        public uint custom_data_14;
        public uint custom_data_15;

        public CustomDataUnitMsg()
        {
            this.custom_data_0 = 0;
            this.custom_data_1 = 0;
            this.custom_data_2 = 0;
            this.custom_data_3 = 0;
            this.custom_data_4 = 0;
            this.custom_data_5 = 0;
            this.custom_data_6 = 0;
            this.custom_data_7 = 0;
            this.custom_data_8 = 0;
            this.custom_data_9 = 0;
            this.custom_data_10 = 0;
            this.custom_data_11 = 0;
            this.custom_data_12 = 0;
            this.custom_data_13 = 0;
            this.custom_data_14 = 0;
            this.custom_data_15 = 0;
        }

        public CustomDataUnitMsg(uint custom_data_0, uint custom_data_1, uint custom_data_2, uint custom_data_3, uint custom_data_4, uint custom_data_5, uint custom_data_6, uint custom_data_7, uint custom_data_8, uint custom_data_9, uint custom_data_10, uint custom_data_11, uint custom_data_12, uint custom_data_13, uint custom_data_14, uint custom_data_15)
        {
            this.custom_data_0 = custom_data_0;
            this.custom_data_1 = custom_data_1;
            this.custom_data_2 = custom_data_2;
            this.custom_data_3 = custom_data_3;
            this.custom_data_4 = custom_data_4;
            this.custom_data_5 = custom_data_5;
            this.custom_data_6 = custom_data_6;
            this.custom_data_7 = custom_data_7;
            this.custom_data_8 = custom_data_8;
            this.custom_data_9 = custom_data_9;
            this.custom_data_10 = custom_data_10;
            this.custom_data_11 = custom_data_11;
            this.custom_data_12 = custom_data_12;
            this.custom_data_13 = custom_data_13;
            this.custom_data_14 = custom_data_14;
            this.custom_data_15 = custom_data_15;
        }

        public static CustomDataUnitMsg Deserialize(MessageDeserializer deserializer) => new CustomDataUnitMsg(deserializer);

        private CustomDataUnitMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.custom_data_0);
            deserializer.Read(out this.custom_data_1);
            deserializer.Read(out this.custom_data_2);
            deserializer.Read(out this.custom_data_3);
            deserializer.Read(out this.custom_data_4);
            deserializer.Read(out this.custom_data_5);
            deserializer.Read(out this.custom_data_6);
            deserializer.Read(out this.custom_data_7);
            deserializer.Read(out this.custom_data_8);
            deserializer.Read(out this.custom_data_9);
            deserializer.Read(out this.custom_data_10);
            deserializer.Read(out this.custom_data_11);
            deserializer.Read(out this.custom_data_12);
            deserializer.Read(out this.custom_data_13);
            deserializer.Read(out this.custom_data_14);
            deserializer.Read(out this.custom_data_15);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.custom_data_0);
            serializer.Write(this.custom_data_1);
            serializer.Write(this.custom_data_2);
            serializer.Write(this.custom_data_3);
            serializer.Write(this.custom_data_4);
            serializer.Write(this.custom_data_5);
            serializer.Write(this.custom_data_6);
            serializer.Write(this.custom_data_7);
            serializer.Write(this.custom_data_8);
            serializer.Write(this.custom_data_9);
            serializer.Write(this.custom_data_10);
            serializer.Write(this.custom_data_11);
            serializer.Write(this.custom_data_12);
            serializer.Write(this.custom_data_13);
            serializer.Write(this.custom_data_14);
            serializer.Write(this.custom_data_15);
        }

        public override string ToString()
        {
            return "CustomDataUnitMsg: " +
            "\ncustom_data_0: " + custom_data_0.ToString() +
            "\ncustom_data_1: " + custom_data_1.ToString() +
            "\ncustom_data_2: " + custom_data_2.ToString() +
            "\ncustom_data_3: " + custom_data_3.ToString() +
            "\ncustom_data_4: " + custom_data_4.ToString() +
            "\ncustom_data_5: " + custom_data_5.ToString() +
            "\ncustom_data_6: " + custom_data_6.ToString() +
            "\ncustom_data_7: " + custom_data_7.ToString() +
            "\ncustom_data_8: " + custom_data_8.ToString() +
            "\ncustom_data_9: " + custom_data_9.ToString() +
            "\ncustom_data_10: " + custom_data_10.ToString() +
            "\ncustom_data_11: " + custom_data_11.ToString() +
            "\ncustom_data_12: " + custom_data_12.ToString() +
            "\ncustom_data_13: " + custom_data_13.ToString() +
            "\ncustom_data_14: " + custom_data_14.ToString() +
            "\ncustom_data_15: " + custom_data_15.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
