//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GripperCyclic_CommandMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/GripperCyclic_Command";
        public override string RosMessageName => k_RosMessageName;

        public GripperCyclic_MessageIdMsg command_id;
        public uint flags;
        public MotorCommandMsg[] motor_cmd;

        public GripperCyclic_CommandMsg()
        {
            this.command_id = new GripperCyclic_MessageIdMsg();
            this.flags = 0;
            this.motor_cmd = new MotorCommandMsg[0];
        }

        public GripperCyclic_CommandMsg(GripperCyclic_MessageIdMsg command_id, uint flags, MotorCommandMsg[] motor_cmd)
        {
            this.command_id = command_id;
            this.flags = flags;
            this.motor_cmd = motor_cmd;
        }

        public static GripperCyclic_CommandMsg Deserialize(MessageDeserializer deserializer) => new GripperCyclic_CommandMsg(deserializer);

        private GripperCyclic_CommandMsg(MessageDeserializer deserializer)
        {
            this.command_id = GripperCyclic_MessageIdMsg.Deserialize(deserializer);
            deserializer.Read(out this.flags);
            deserializer.Read(out this.motor_cmd, MotorCommandMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command_id);
            serializer.Write(this.flags);
            serializer.WriteLength(this.motor_cmd);
            serializer.Write(this.motor_cmd);
        }

        public override string ToString()
        {
            return "GripperCyclic_CommandMsg: " +
            "\ncommand_id: " + command_id.ToString() +
            "\nflags: " + flags.ToString() +
            "\nmotor_cmd: " + System.String.Join(", ", motor_cmd.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
