//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class GripperCyclic_CustomDataMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/GripperCyclic_CustomData";
        public override string RosMessageName => k_RosMessageName;

        public GripperCyclic_MessageIdMsg custom_data_id;
        public CustomDataUnitMsg gripper_custom_data;
        public CustomDataUnitMsg[] motor_custom_data;

        public GripperCyclic_CustomDataMsg()
        {
            this.custom_data_id = new GripperCyclic_MessageIdMsg();
            this.gripper_custom_data = new CustomDataUnitMsg();
            this.motor_custom_data = new CustomDataUnitMsg[0];
        }

        public GripperCyclic_CustomDataMsg(GripperCyclic_MessageIdMsg custom_data_id, CustomDataUnitMsg gripper_custom_data, CustomDataUnitMsg[] motor_custom_data)
        {
            this.custom_data_id = custom_data_id;
            this.gripper_custom_data = gripper_custom_data;
            this.motor_custom_data = motor_custom_data;
        }

        public static GripperCyclic_CustomDataMsg Deserialize(MessageDeserializer deserializer) => new GripperCyclic_CustomDataMsg(deserializer);

        private GripperCyclic_CustomDataMsg(MessageDeserializer deserializer)
        {
            this.custom_data_id = GripperCyclic_MessageIdMsg.Deserialize(deserializer);
            this.gripper_custom_data = CustomDataUnitMsg.Deserialize(deserializer);
            deserializer.Read(out this.motor_custom_data, CustomDataUnitMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.custom_data_id);
            serializer.Write(this.gripper_custom_data);
            serializer.WriteLength(this.motor_custom_data);
            serializer.Write(this.motor_custom_data);
        }

        public override string ToString()
        {
            return "GripperCyclic_CustomDataMsg: " +
            "\ncustom_data_id: " + custom_data_id.ToString() +
            "\ngripper_custom_data: " + gripper_custom_data.ToString() +
            "\nmotor_custom_data: " + System.String.Join(", ", motor_custom_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
