//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class InterconnectCyclic_FeedbackMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/InterconnectCyclic_Feedback";
        public override string RosMessageName => k_RosMessageName;

        public InterconnectCyclic_MessageIdMsg feedback_id;
        public uint status_flags;
        public uint jitter_comm;
        public float imu_acceleration_x;
        public float imu_acceleration_y;
        public float imu_acceleration_z;
        public float imu_angular_velocity_x;
        public float imu_angular_velocity_y;
        public float imu_angular_velocity_z;
        public float voltage;
        public float temperature_core;
        public uint fault_bank_a;
        public uint fault_bank_b;
        public uint warning_bank_a;
        public uint warning_bank_b;
        public InterconnectCyclic_Feedback_tool_feedbackMsg oneof_tool_feedback;

        public InterconnectCyclic_FeedbackMsg()
        {
            this.feedback_id = new InterconnectCyclic_MessageIdMsg();
            this.status_flags = 0;
            this.jitter_comm = 0;
            this.imu_acceleration_x = 0.0f;
            this.imu_acceleration_y = 0.0f;
            this.imu_acceleration_z = 0.0f;
            this.imu_angular_velocity_x = 0.0f;
            this.imu_angular_velocity_y = 0.0f;
            this.imu_angular_velocity_z = 0.0f;
            this.voltage = 0.0f;
            this.temperature_core = 0.0f;
            this.fault_bank_a = 0;
            this.fault_bank_b = 0;
            this.warning_bank_a = 0;
            this.warning_bank_b = 0;
            this.oneof_tool_feedback = new InterconnectCyclic_Feedback_tool_feedbackMsg();
        }

        public InterconnectCyclic_FeedbackMsg(InterconnectCyclic_MessageIdMsg feedback_id, uint status_flags, uint jitter_comm, float imu_acceleration_x, float imu_acceleration_y, float imu_acceleration_z, float imu_angular_velocity_x, float imu_angular_velocity_y, float imu_angular_velocity_z, float voltage, float temperature_core, uint fault_bank_a, uint fault_bank_b, uint warning_bank_a, uint warning_bank_b, InterconnectCyclic_Feedback_tool_feedbackMsg oneof_tool_feedback)
        {
            this.feedback_id = feedback_id;
            this.status_flags = status_flags;
            this.jitter_comm = jitter_comm;
            this.imu_acceleration_x = imu_acceleration_x;
            this.imu_acceleration_y = imu_acceleration_y;
            this.imu_acceleration_z = imu_acceleration_z;
            this.imu_angular_velocity_x = imu_angular_velocity_x;
            this.imu_angular_velocity_y = imu_angular_velocity_y;
            this.imu_angular_velocity_z = imu_angular_velocity_z;
            this.voltage = voltage;
            this.temperature_core = temperature_core;
            this.fault_bank_a = fault_bank_a;
            this.fault_bank_b = fault_bank_b;
            this.warning_bank_a = warning_bank_a;
            this.warning_bank_b = warning_bank_b;
            this.oneof_tool_feedback = oneof_tool_feedback;
        }

        public static InterconnectCyclic_FeedbackMsg Deserialize(MessageDeserializer deserializer) => new InterconnectCyclic_FeedbackMsg(deserializer);

        private InterconnectCyclic_FeedbackMsg(MessageDeserializer deserializer)
        {
            this.feedback_id = InterconnectCyclic_MessageIdMsg.Deserialize(deserializer);
            deserializer.Read(out this.status_flags);
            deserializer.Read(out this.jitter_comm);
            deserializer.Read(out this.imu_acceleration_x);
            deserializer.Read(out this.imu_acceleration_y);
            deserializer.Read(out this.imu_acceleration_z);
            deserializer.Read(out this.imu_angular_velocity_x);
            deserializer.Read(out this.imu_angular_velocity_y);
            deserializer.Read(out this.imu_angular_velocity_z);
            deserializer.Read(out this.voltage);
            deserializer.Read(out this.temperature_core);
            deserializer.Read(out this.fault_bank_a);
            deserializer.Read(out this.fault_bank_b);
            deserializer.Read(out this.warning_bank_a);
            deserializer.Read(out this.warning_bank_b);
            this.oneof_tool_feedback = InterconnectCyclic_Feedback_tool_feedbackMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.feedback_id);
            serializer.Write(this.status_flags);
            serializer.Write(this.jitter_comm);
            serializer.Write(this.imu_acceleration_x);
            serializer.Write(this.imu_acceleration_y);
            serializer.Write(this.imu_acceleration_z);
            serializer.Write(this.imu_angular_velocity_x);
            serializer.Write(this.imu_angular_velocity_y);
            serializer.Write(this.imu_angular_velocity_z);
            serializer.Write(this.voltage);
            serializer.Write(this.temperature_core);
            serializer.Write(this.fault_bank_a);
            serializer.Write(this.fault_bank_b);
            serializer.Write(this.warning_bank_a);
            serializer.Write(this.warning_bank_b);
            serializer.Write(this.oneof_tool_feedback);
        }

        public override string ToString()
        {
            return "InterconnectCyclic_FeedbackMsg: " +
            "\nfeedback_id: " + feedback_id.ToString() +
            "\nstatus_flags: " + status_flags.ToString() +
            "\njitter_comm: " + jitter_comm.ToString() +
            "\nimu_acceleration_x: " + imu_acceleration_x.ToString() +
            "\nimu_acceleration_y: " + imu_acceleration_y.ToString() +
            "\nimu_acceleration_z: " + imu_acceleration_z.ToString() +
            "\nimu_angular_velocity_x: " + imu_angular_velocity_x.ToString() +
            "\nimu_angular_velocity_y: " + imu_angular_velocity_y.ToString() +
            "\nimu_angular_velocity_z: " + imu_angular_velocity_z.ToString() +
            "\nvoltage: " + voltage.ToString() +
            "\ntemperature_core: " + temperature_core.ToString() +
            "\nfault_bank_a: " + fault_bank_a.ToString() +
            "\nfault_bank_b: " + fault_bank_b.ToString() +
            "\nwarning_bank_a: " + warning_bank_a.ToString() +
            "\nwarning_bank_b: " + warning_bank_b.ToString() +
            "\noneof_tool_feedback: " + oneof_tool_feedback.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
