//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class InterconnectCyclic_ServiceVersionMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/InterconnectCyclic_ServiceVersion";
        public override string RosMessageName => k_RosMessageName;

        public const uint RESERVED_0 = 0;
        public const uint CURRENT_VERSION = 1;

        public InterconnectCyclic_ServiceVersionMsg()
        {
        }
        public static InterconnectCyclic_ServiceVersionMsg Deserialize(MessageDeserializer deserializer) => new InterconnectCyclic_ServiceVersionMsg(deserializer);

        private InterconnectCyclic_ServiceVersionMsg(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "InterconnectCyclic_ServiceVersionMsg: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
