//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class InterconnectCyclic_Feedback_tool_feedbackMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/InterconnectCyclic_Feedback_tool_feedback";
        public override string RosMessageName => k_RosMessageName;

        public GripperCyclic_FeedbackMsg[] gripper_feedback;

        public InterconnectCyclic_Feedback_tool_feedbackMsg()
        {
            this.gripper_feedback = new GripperCyclic_FeedbackMsg[0];
        }

        public InterconnectCyclic_Feedback_tool_feedbackMsg(GripperCyclic_FeedbackMsg[] gripper_feedback)
        {
            this.gripper_feedback = gripper_feedback;
        }

        public static InterconnectCyclic_Feedback_tool_feedbackMsg Deserialize(MessageDeserializer deserializer) => new InterconnectCyclic_Feedback_tool_feedbackMsg(deserializer);

        private InterconnectCyclic_Feedback_tool_feedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper_feedback, GripperCyclic_FeedbackMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.gripper_feedback);
            serializer.Write(this.gripper_feedback);
        }

        public override string ToString()
        {
            return "InterconnectCyclic_Feedback_tool_feedbackMsg: " +
            "\ngripper_feedback: " + System.String.Join(", ", gripper_feedback.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
