//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class InterconnectCyclic_CustomData_tool_customDataMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/InterconnectCyclic_CustomData_tool_customData";
        public override string RosMessageName => k_RosMessageName;

        public GripperCyclic_CustomDataMsg[] gripper_custom_data;

        public InterconnectCyclic_CustomData_tool_customDataMsg()
        {
            this.gripper_custom_data = new GripperCyclic_CustomDataMsg[0];
        }

        public InterconnectCyclic_CustomData_tool_customDataMsg(GripperCyclic_CustomDataMsg[] gripper_custom_data)
        {
            this.gripper_custom_data = gripper_custom_data;
        }

        public static InterconnectCyclic_CustomData_tool_customDataMsg Deserialize(MessageDeserializer deserializer) => new InterconnectCyclic_CustomData_tool_customDataMsg(deserializer);

        private InterconnectCyclic_CustomData_tool_customDataMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper_custom_data, GripperCyclic_CustomDataMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.gripper_custom_data);
            serializer.Write(this.gripper_custom_data);
        }

        public override string ToString()
        {
            return "InterconnectCyclic_CustomData_tool_customDataMsg: " +
            "\ngripper_custom_data: " + System.String.Join(", ", gripper_custom_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
