//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class InterconnectCyclic_MessageIdMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/InterconnectCyclic_MessageId";
        public override string RosMessageName => k_RosMessageName;

        public uint identifier;

        public InterconnectCyclic_MessageIdMsg()
        {
            this.identifier = 0;
        }

        public InterconnectCyclic_MessageIdMsg(uint identifier)
        {
            this.identifier = identifier;
        }

        public static InterconnectCyclic_MessageIdMsg Deserialize(MessageDeserializer deserializer) => new InterconnectCyclic_MessageIdMsg(deserializer);

        private InterconnectCyclic_MessageIdMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.identifier);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.identifier);
        }

        public override string ToString()
        {
            return "InterconnectCyclic_MessageIdMsg: " +
            "\nidentifier: " + identifier.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
