//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class InterconnectCyclic_Command_tool_commandMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/InterconnectCyclic_Command_tool_command";
        public override string RosMessageName => k_RosMessageName;

        public GripperCyclic_CommandMsg[] gripper_command;

        public InterconnectCyclic_Command_tool_commandMsg()
        {
            this.gripper_command = new GripperCyclic_CommandMsg[0];
        }

        public InterconnectCyclic_Command_tool_commandMsg(GripperCyclic_CommandMsg[] gripper_command)
        {
            this.gripper_command = gripper_command;
        }

        public static InterconnectCyclic_Command_tool_commandMsg Deserialize(MessageDeserializer deserializer) => new InterconnectCyclic_Command_tool_commandMsg(deserializer);

        private InterconnectCyclic_Command_tool_commandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gripper_command, GripperCyclic_CommandMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.gripper_command);
            serializer.Write(this.gripper_command);
        }

        public override string ToString()
        {
            return "InterconnectCyclic_Command_tool_commandMsg: " +
            "\ngripper_command: " + System.String.Join(", ", gripper_command.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
