//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.KortexDriver
{
    [Serializable]
    public class JointAngleMsg : Message
    {
        public const string k_RosMessageName = "kortex_driver/JointAngle";
        public override string RosMessageName => k_RosMessageName;

        public uint joint_identifier;
        public float value;

        public JointAngleMsg()
        {
            this.joint_identifier = 0;
            this.value = 0.0f;
        }

        public JointAngleMsg(uint joint_identifier, float value)
        {
            this.joint_identifier = joint_identifier;
            this.value = value;
        }

        public static JointAngleMsg Deserialize(MessageDeserializer deserializer) => new JointAngleMsg(deserializer);

        private JointAngleMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joint_identifier);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joint_identifier);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "JointAngleMsg: " +
            "\njoint_identifier: " + joint_identifier.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
